spring:
  application:
    name: go-crawler
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  data:
    mongodb:
      uri: mongodb://admin:123456@192.168.1.11:27017/go-crawler
server:
  port: 18080

file:
  upload-dir: D:/Workspaces/go-crawler/uploads/